package vn.com.nsmv.entity;

import java.util.*;

import javax.persistence.*;

/**
 * Trans generated by hbm2java
 */
@Entity
@Table(name = "trans")
public class Trans implements java.io.Serializable
{

	private NyukoId id;
	private Date nykoDate;
	private Date sukkaDate;
	private Integer status;
	private Integer deleteFlg;
	private Date createDate;
	private Date updateDate;

	public Trans()
	{
	}

	public Trans(
		Date nykoDate,
		Date sukkaDate,
		Integer status,
		Integer deleteFlg,
		Date createDate,
		Date updateDate)
	{
		this.nykoDate = nykoDate;
		this.sukkaDate = sukkaDate;
		this.status = status;
		this.deleteFlg = deleteFlg;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "szNo", column = @Column(name = "SZ_NO", nullable = false, length = 8)),
			@AttributeOverride(name = "sokoCd", column = @Column(name = "SOKO_CD", nullable = false, length = 9)) })
	public NyukoId getId()
	{
		return this.id;
	}

	public void setId(NyukoId id)
	{
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NYKO_DATE", length = 19)
	public Date getNykoDate()
	{
		return this.nykoDate;
	}

	public void setNykoDate(Date nykoDate)
	{
		this.nykoDate = nykoDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SUKKA_DATE", length = 19)
	public Date getSukkaDate()
	{
		return this.sukkaDate;
	}

	public void setSukkaDate(Date sukkaDate)
	{
		this.sukkaDate = sukkaDate;
	}

	@Column(name = "STATUS")
	public Integer getStatus()
	{
		return this.status;
	}

	public void setStatus(Integer status)
	{
		this.status = status;
	}

	@Column(name = "DELETE_FLG")
	public Integer getDeleteFlg()
	{
		return this.deleteFlg;
	}

	public void setDeleteFlg(Integer deleteFlg)
	{
		this.deleteFlg = deleteFlg;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate()
	{
		return this.createDate;
	}

	public void setCreateDate(Date createDate)
	{
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate()
	{
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate)
	{
		this.updateDate = updateDate;
	}

}
